### ISSUE TITLE
Allow blacklist/whitelist of types to convert

### ISSUE THREAD

**Issue by SimenB** [storybooks/telejson#2]
Hey!

I'd love to explore using this module to pass config to and from workers in Jest, but to do so, I'd need an API for ensuring functions and class instances are not serialized.

The reason for this is the closures and state aren't serialized, and I think it will be very confusing and hard to debug for user (of Jest).

**Comment by ndelangen** [comment]
@SimenB sure that sounds like something we could support!

**Comment by ndelangen** [comment]
Would you expect a class Instance to be completely ignored and removed or it's properties still be serialized, but as a plain object?

**Comment by SimenB** [comment]
The end goal would be for anything encompassing state (through instances, closures etc) to be ignored/made to throw. So I guess I'd expect it to be ignored since removing just functions from it seems odd. Right?

**Comment by SimenB** [comment]
Solved in #3
