### ISSUE TITLE
safe-eval is intended only for using with Node

### ISSUE THREAD

**Issue by Hypnosphi** [storybooks/telejson#4]
See README.md 
https://github.com/hacksparrow/safe-eval

This package runs in browers (e.g. in `@storybook/channel-postmessage`), so you probably need to find some alternatives

**Comment by Hypnosphi** [comment]
Given that safe-eval [isn't](https://github.com/hacksparrow/safe-eval/issues/16) actually safe, maybe just using plain old `eval` is the way to go

**Comment by ndelangen** [comment]
👌

**Comment by ndelangen** [comment]
Fixed in 2.0.0
