### ISSUE TITLE
Replacing `safe-eval` with safer alternative?

### ISSUE THREAD

**Issue by kutyepov** [storybooks/telejson#6]
`safe-eval` <= 0.3.x had security vulnerability which were **partially** addressed in 0.4.x versions.
Looking at this [comment](https://github.com/hacksparrow/safe-eval/issues/5#issuecomment-415904706), it looks like `safe-eval` is still vulnerable.
Should we try to replace this package with safer one?

**Comment by adwilk** [comment]
It seems safe-eval is not used anymore and so can be safely removed from the package dependencies without a replacement. This is the commit that removed usage of safe-eval https://github.com/storybooks/telejson/commit/650a755cb4ce3299730d6b447e269f9d3e41630f

**Comment by vvanmol** [comment]
Hello,

The package telejson@2.1.1 is still referencing safe-eval@^0.4.1 in its package.json which is blocked by our NPM Package vulnerability scanner in our company.

Could you please remove safe-eval from the package.json file and make a new release of telejson ?  Especially as telejson doesn't require it anymore...

Thanks !

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
@kutyepov's PR is merged, and released in v2.2.0
